# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043d\u0430\u0432\u044b\u043a\u0430'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='previous_categories',
            field=models.ManyToManyField(blank=True, to='sheets.Skill', verbose_name='\u041f\u0440\u0435\u0434\u044b\u0434\u0443\u0449\u0438\u0435 \u043d\u0430\u0432\u044b\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='taxonomy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='sheets.SkillType', verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u0438'),
        ),
    ]
