# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20181118_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': '\u041d\u0430\u0432\u044b\u043a', 'verbose_name_plural': '\u041d\u0430\u0432\u044b\u043a\u0438'},
        ),
        migrations.AlterModelOptions(
            name='skillinstance',
            options={'verbose_name': '\u041d\u0430\u0431\u043b\u044e\u0434\u0435\u043d\u0438\u0435 \u043d\u0430\u0432\u044b\u043a\u0430', 'verbose_name_plural': '\u041d\u0430\u0431\u043b\u044e\u0434\u0435\u043d\u0438\u044f \u043d\u0430\u0432\u044b\u043a\u043e\u0432'},
        ),
        migrations.AlterModelOptions(
            name='skilltype',
            options={'verbose_name': '\u0422\u0438\u043f \u043d\u0430\u0432\u044b\u043a\u0430', 'verbose_name_plural': '\u0422\u0438\u043f\u044b \u043d\u0430\u0432\u044b\u043a\u043e\u0432'},
        ),
        migrations.AlterModelOptions(
            name='spreadsheet',
            options={'verbose_name': '\u0422\u0435\u0442\u0440\u0430\u0434\u044c \u043d\u0430\u0431\u043b\u044e\u0434\u0435\u043d\u0438\u0439', 'verbose_name_plural': '\u0422\u0435\u0442\u0440\u0430\u0434\u0438 \u043d\u0430\u0431\u043b\u044e\u0434\u0435\u043d\u0438\u0439'},
        ),
        migrations.AddField(
            model_name='skillinstance',
            name='skill_level',
            field=models.IntegerField(db_index=True, default=12, verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c \u043d\u0430\u0432\u044b\u043a\u0430'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skillinstance',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_instances', to='sheets.Skill', verbose_name='\u041d\u0430\u0432\u044b\u043a'),
        ),
        migrations.AlterField(
            model_name='skillinstance',
            name='spreadsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_instances', to='sheets.SpreadSheet', verbose_name='\u0422\u0435\u0442\u0440\u0430\u0434\u044c \u043d\u0430\u0431\u043b\u044e\u0434\u0435\u043d\u0438\u0439'),
        ),
    ]
