# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_auto_20181118_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='amount_of_next_skills',
            field=models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0434\u043e\u0447\u0435\u0440\u043d\u0438\u0445 \u043d\u0430\u0432\u044b\u043a\u043e\u0432'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='previous_categories_text',
            field=models.CharField(db_index=True, default='', max_length=1000, verbose_name='\u041f\u0440\u0435\u0434\u044b\u0434\u0443\u0449\u0438\u0435 \u043d\u0430\u0432\u044b\u043a\u0438'),
            preserve_default=False,
        ),
    ]
