# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_auto_20181118_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='previous_categories_text',
            field=models.CharField(db_index=True, default='', max_length=1000, verbose_name='\u041f\u0443\u0442\u044c \u043a \u043d\u0430\u0432\u044b\u043a\u0443'),
            preserve_default=False,
        ),
    ]
